/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendasComissoesRouteImport } from './routes/_authenticated/vendas-comissoes'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedOrcadoRealizadoRouteImport } from './routes/_authenticated/orcado-realizado'
import { Route as AuthenticatedLojasRouteImport } from './routes/_authenticated/lojas'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedFinanceirasRouteImport } from './routes/_authenticated/financeiras'
import { Route as AuthenticatedExtratoFinanceiroRouteImport } from './routes/_authenticated/extrato-financeiro'
import { Route as AuthenticatedExtratoRouteImport } from './routes/_authenticated/extrato'
import { Route as AuthenticatedDetalhamentoRouteImport } from './routes/_authenticated/detalhamento'
import { Route as AuthenticatedDashboardVendasRouteImport } from './routes/_authenticated/dashboard-vendas'
import { Route as AuthenticatedDashboardFinanceiroRouteImport } from './routes/_authenticated/dashboard-financeiro'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated/contas-pagar'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated/caixa'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasComissoesRoute =
  AuthenticatedVendasComissoesRouteImport.update({
    id: '/vendas-comissoes',
    path: '/vendas-comissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcadoRealizadoRoute =
  AuthenticatedOrcadoRealizadoRouteImport.update({
    id: '/orcado-realizado',
    path: '/orcado-realizado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLojasRoute = AuthenticatedLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceirasRoute =
  AuthenticatedFinanceirasRouteImport.update({
    id: '/financeiras',
    path: '/financeiras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtratoFinanceiroRoute =
  AuthenticatedExtratoFinanceiroRouteImport.update({
    id: '/extrato-financeiro',
    path: '/extrato-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExtratoRoute = AuthenticatedExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDetalhamentoRoute =
  AuthenticatedDetalhamentoRouteImport.update({
    id: '/detalhamento',
    path: '/detalhamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardVendasRoute =
  AuthenticatedDashboardVendasRouteImport.update({
    id: '/dashboard-vendas',
    path: '/dashboard-vendas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardFinanceiroRoute =
  AuthenticatedDashboardFinanceiroRouteImport.update({
    id: '/dashboard-financeiro',
    path: '/dashboard-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas': typeof AuthenticatedContasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/dashboard-financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard-vendas': typeof AuthenticatedDashboardVendasRoute
  '/detalhamento': typeof AuthenticatedDetalhamentoRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/extrato-financeiro': typeof AuthenticatedExtratoFinanceiroRoute
  '/financeiras': typeof AuthenticatedFinanceirasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/orcado-realizado': typeof AuthenticatedOrcadoRealizadoRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-comissoes': typeof AuthenticatedVendasComissoesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas': typeof AuthenticatedContasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/dashboard-financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard-vendas': typeof AuthenticatedDashboardVendasRoute
  '/detalhamento': typeof AuthenticatedDetalhamentoRoute
  '/extrato': typeof AuthenticatedExtratoRoute
  '/extrato-financeiro': typeof AuthenticatedExtratoFinanceiroRoute
  '/financeiras': typeof AuthenticatedFinanceirasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/orcado-realizado': typeof AuthenticatedOrcadoRealizadoRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-comissoes': typeof AuthenticatedVendasComissoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/dashboard-financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/_authenticated/dashboard-vendas': typeof AuthenticatedDashboardVendasRoute
  '/_authenticated/detalhamento': typeof AuthenticatedDetalhamentoRoute
  '/_authenticated/extrato': typeof AuthenticatedExtratoRoute
  '/_authenticated/extrato-financeiro': typeof AuthenticatedExtratoFinanceiroRoute
  '/_authenticated/financeiras': typeof AuthenticatedFinanceirasRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/lojas': typeof AuthenticatedLojasRoute
  '/_authenticated/orcado-realizado': typeof AuthenticatedOrcadoRealizadoRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/vendas-comissoes': typeof AuthenticatedVendasComissoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/caixa'
    | '/cartoes'
    | '/categorias'
    | '/clientes'
    | '/comissoes'
    | '/conciliacao'
    | '/contas'
    | '/contas-pagar'
    | '/contas-receber'
    | '/dashboard-financeiro'
    | '/dashboard-vendas'
    | '/detalhamento'
    | '/extrato'
    | '/extrato-financeiro'
    | '/financeiras'
    | '/fornecedores'
    | '/lojas'
    | '/orcado-realizado'
    | '/orcamento'
    | '/usuarios'
    | '/vendas'
    | '/vendas-comissoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alertas'
    | '/caixa'
    | '/cartoes'
    | '/categorias'
    | '/clientes'
    | '/comissoes'
    | '/conciliacao'
    | '/contas'
    | '/contas-pagar'
    | '/contas-receber'
    | '/dashboard-financeiro'
    | '/dashboard-vendas'
    | '/detalhamento'
    | '/extrato'
    | '/extrato-financeiro'
    | '/financeiras'
    | '/fornecedores'
    | '/lojas'
    | '/orcado-realizado'
    | '/orcamento'
    | '/usuarios'
    | '/vendas'
    | '/vendas-comissoes'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/caixa'
    | '/_authenticated/cartoes'
    | '/_authenticated/categorias'
    | '/_authenticated/clientes'
    | '/_authenticated/comissoes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/contas'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/dashboard-financeiro'
    | '/_authenticated/dashboard-vendas'
    | '/_authenticated/detalhamento'
    | '/_authenticated/extrato'
    | '/_authenticated/extrato-financeiro'
    | '/_authenticated/financeiras'
    | '/_authenticated/fornecedores'
    | '/_authenticated/lojas'
    | '/_authenticated/orcado-realizado'
    | '/_authenticated/orcamento'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendas'
    | '/_authenticated/vendas-comissoes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas-comissoes': {
      id: '/_authenticated/vendas-comissoes'
      path: '/vendas-comissoes'
      fullPath: '/vendas-comissoes'
      preLoaderRoute: typeof AuthenticatedVendasComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcado-realizado': {
      id: '/_authenticated/orcado-realizado'
      path: '/orcado-realizado'
      fullPath: '/orcado-realizado'
      preLoaderRoute: typeof AuthenticatedOrcadoRealizadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojas': {
      id: '/_authenticated/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AuthenticatedLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiras': {
      id: '/_authenticated/financeiras'
      path: '/financeiras'
      fullPath: '/financeiras'
      preLoaderRoute: typeof AuthenticatedFinanceirasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato-financeiro': {
      id: '/_authenticated/extrato-financeiro'
      path: '/extrato-financeiro'
      fullPath: '/extrato-financeiro'
      preLoaderRoute: typeof AuthenticatedExtratoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extrato': {
      id: '/_authenticated/extrato'
      path: '/extrato'
      fullPath: '/extrato'
      preLoaderRoute: typeof AuthenticatedExtratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/detalhamento': {
      id: '/_authenticated/detalhamento'
      path: '/detalhamento'
      fullPath: '/detalhamento'
      preLoaderRoute: typeof AuthenticatedDetalhamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-vendas': {
      id: '/_authenticated/dashboard-vendas'
      path: '/dashboard-vendas'
      fullPath: '/dashboard-vendas'
      preLoaderRoute: typeof AuthenticatedDashboardVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-financeiro': {
      id: '/_authenticated/dashboard-financeiro'
      path: '/dashboard-financeiro'
      fullPath: '/dashboard-financeiro'
      preLoaderRoute: typeof AuthenticatedDashboardFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedDashboardFinanceiroRoute: typeof AuthenticatedDashboardFinanceiroRoute
  AuthenticatedDashboardVendasRoute: typeof AuthenticatedDashboardVendasRoute
  AuthenticatedDetalhamentoRoute: typeof AuthenticatedDetalhamentoRoute
  AuthenticatedExtratoRoute: typeof AuthenticatedExtratoRoute
  AuthenticatedExtratoFinanceiroRoute: typeof AuthenticatedExtratoFinanceiroRoute
  AuthenticatedFinanceirasRoute: typeof AuthenticatedFinanceirasRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedLojasRoute: typeof AuthenticatedLojasRoute
  AuthenticatedOrcadoRealizadoRoute: typeof AuthenticatedOrcadoRealizadoRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedVendasComissoesRoute: typeof AuthenticatedVendasComissoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedCartoesRoute: AuthenticatedCartoesRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedDashboardFinanceiroRoute: AuthenticatedDashboardFinanceiroRoute,
  AuthenticatedDashboardVendasRoute: AuthenticatedDashboardVendasRoute,
  AuthenticatedDetalhamentoRoute: AuthenticatedDetalhamentoRoute,
  AuthenticatedExtratoRoute: AuthenticatedExtratoRoute,
  AuthenticatedExtratoFinanceiroRoute: AuthenticatedExtratoFinanceiroRoute,
  AuthenticatedFinanceirasRoute: AuthenticatedFinanceirasRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedLojasRoute: AuthenticatedLojasRoute,
  AuthenticatedOrcadoRealizadoRoute: AuthenticatedOrcadoRealizadoRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedVendasComissoesRoute: AuthenticatedVendasComissoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
