/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedLojasRouteImport } from './routes/_authenticated/lojas'
import { Route as AuthenticatedFinanceirasRouteImport } from './routes/_authenticated/financeiras'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLojasRoute = AuthenticatedLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceirasRoute =
  AuthenticatedFinanceirasRouteImport.update({
    id: '/financeiras',
    path: '/financeiras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas': typeof AuthenticatedContasRoute
  '/financeiras': typeof AuthenticatedFinanceirasRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/contas': typeof AuthenticatedContasRoute
  '/financeiras': typeof AuthenticatedFinanceirasRoute
  '/lojas': typeof AuthenticatedLojasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/financeiras': typeof AuthenticatedFinanceirasRoute
  '/_authenticated/lojas': typeof AuthenticatedLojasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/conciliacao'
    | '/contas'
    | '/financeiras'
    | '/lojas'
    | '/usuarios'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alertas'
    | '/conciliacao'
    | '/contas'
    | '/financeiras'
    | '/lojas'
    | '/usuarios'
    | '/vendas'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/conciliacao'
    | '/_authenticated/contas'
    | '/_authenticated/financeiras'
    | '/_authenticated/lojas'
    | '/_authenticated/usuarios'
    | '/_authenticated/vendas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojas': {
      id: '/_authenticated/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof AuthenticatedLojasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiras': {
      id: '/_authenticated/financeiras'
      path: '/financeiras'
      fullPath: '/financeiras'
      preLoaderRoute: typeof AuthenticatedFinanceirasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedFinanceirasRoute: typeof AuthenticatedFinanceirasRoute
  AuthenticatedLojasRoute: typeof AuthenticatedLojasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedFinanceirasRoute: AuthenticatedFinanceirasRoute,
  AuthenticatedLojasRoute: AuthenticatedLojasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
